name: docs

on:
  push:
    branches: [ master, docs ]

  workflow_dispatch:

jobs:
  build:
    env:
      NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          path: './src/'

      - uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '11'

      - name: generate docs
        run: |
          cd src
          make docs
      - uses: actions/checkout@v3
        with:
          ref: 'gh-pages'
          path: './web/'

      - name: promote
        run: |
          cd web
          cp -rp ../src/sdk/build/docs/* index
      - uses: EndBug/add-and-commit@v9
        with:
          message: 'publish generated docs'
          add: 'index'
          cwd: './web/'
          author_name: 'Relay Pro builder'
          author_email: 'info@relaypro.com'
          push: true
